
FROM alpine:3.16

ENV NODE_VERSION 16.19.0

RUN npm i -g serve

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5000

CMD [ "serve", "-s", "dist" ]